# Generated by Django 4.0.6 on 2022-10-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('created', models.DateField()),
                ('link', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=255)),
            ],
        ),
    ]
